name: flutter_jsonform
version: 0.0.1
description: >
  flutter_jsonform is simple plugin that allows you to dynamically create forms based on json definition.
homepage: https://github.com/version-two/flutter_jsonform

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  widget_extensions:
    git: git@github.com:canewsin/widget_extensions.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
